# Generated by Django 3.0.8 on 2020-11-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('Return_ref', models.IntegerField()),
                ('issue', models.CharField(max_length=100)),
                ('root_cause', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
