# Generated by Django 3.0.8 on 2020-11-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncr_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productncr',
            options={'ordering': ['-id'], 'verbose_name': 'Product NCR'},
        ),
        migrations.RenameField(
            model_name='productncr',
            old_name='Return_ref',
            new_name='return_ref',
        ),
    ]
